name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths: [ "react-child-app/**", "shared-res/**", "docker-deploy/**", ".github/workflows/**" ]

jobs:
  deploy-react-child:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to server
      if: ${{ !env.ACT }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.DEPLOY_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_DEPLOY_KEY }}
        script: |
          cd ${{ vars.PROJECT_PATH }}
          make update ENV_FILE_NAME=.env.react-child
